### ISSUE TITLE
Invalid deposit data generated when connecting to testnet prysm node

### ISSUE THREAD

**Issue by OisinKyne** [wealdtech/ethdo#33]
Hi Jim, 

This issue may be on the Prysm side, but going to open here to start. When generating a deposit data for a validator using `--connection` to a prysm pyrmont node, the `forkversion` is set incorrectly, resulting in an invalid deposit. Using `--forkversion 0x00002009` instead will generate a valid deposit.

When connecting to a Prysm node, the resulting deposit data has `"fork_version": "0x00000000"`, instead of `"fork_version": "0x00002009"`, which means the `deposit_data_root` is wrong. Full output below:

Invalid:
```
[{"name": "Deposit for Validator/1", "account": "Validator/1", "pubkey": "0x96add68b6c5b4f01df7271982c90a3e29e3301d6bcd669786cf64fb61d9a023c572cef3e8ff1e1d338ac8b7f71ce6534", "withdrawal_credentials": "<don't want to dox someone, let me know if its crucial>", "signature": "0x88ef1f142f06fcb57c52be8e33b052c4d0262eb0195516a72e817a02685d282763ed6d48a4948046847b7c12a82a4c1219186d5eeed688c72cf88050251848f3202df37e18ea977ab42de338ac497d26d9ffbefb79d76390792abfde966ac304", "amount": 32000000000, "deposit_data_root": "0xfcc3dda871de66f2e3f0e45334e5221a3b9846a9564b2c19811e25ec2c764492", "deposit_message_root": "0x03794b1e359947d5dd6216daed850a644cc339bbf80da49fcc3adc544ab1d447", "fork_version": "0x00000000", "version": 3}]
```

Valid:
```
[{"name": "Deposit for Validator/1", "account": "Validator/1", "pubkey": "0x96add68b6c5b4f01df7271982c90a3e29e3301d6bcd669786cf64fb61d9a023c572cef3e8ff1e1d338ac8b7f71ce6534", "withdrawal_credentials": "<don't want to dox someone, let me know if its crucial>", "signature": "0x879af46619b0a1cdb31f1d4852efbab3fa457bfc44b2324ae4e00f3296f6af479b074fa2906d9930a0cd0485784599020c408262f67e85d6316f1c0aa259cb1f6bf9f5e000d8f559ca075edd4a3814980bcdc822115a9cedc0834bdf42799d4a", "amount": 32000000000, "deposit_data_root": "0xa7070a4cd11cc9c3aabbfc13164b79722ea9de437b4c28004cd75ccfdb4476b0", "deposit_message_root": "0x03794b1e359947d5dd6216daed850a644cc339bbf80da49fcc3adc544ab1d447", "fork_version": "0x00002009", "version": 3}]
```

Versions:
ethdo docker `1.8.0`
prysm docker `v1.3.2`

Extra Notes:
Generated this while Prysm is syncing to chain head, I can repeat this tomorrow when fully synced to see if I get a different result.

**Comment by OisinKyne** [comment]
Adding a cheeky CC to @prestonvanloon to put this on his radar ahead of time 😬

**Comment by mcdee** [comment]
Thanks for reporting this issue.  This is down to ethdo, although it's more a documentation error than a code error.

The code was changed a while back (a little while before mainnet launch) to default to the mainnet fork version unless an override was provided explicitly with the `--forkversion` option.  The rationale behind this is that it possible for users to configure ethdo to point to a testnet node and forget about the fact, then run a `depositdata` for what should be mainnet and end up with bad deposit data.  Given that there are two possible versions of "wrong" here, it was decided that erring on the side of creating incorrect testnet deposits was a much better result than creating incorrect mainnet deposits.

So the issue is that the documentation is still talking about fetching the fork version from the node, when it no longer does this.  I'll take a look to see where this is mentioned and update the documentation accordingly.

**Comment by OisinKyne** [comment]
Seems very reasonable, it's definitely preferably to lean towards defaulting to 0x0 in that case, the downside of the other type of wrong is a lot worse. Looking back, I don't think the docs even mention connection string anymore, so this is quite likely a function of me not updating my code on my end. https://github.com/wealdtech/ethdo/blob/master/docs/usage.md#depositdata probably nothing to change in that regard, thanks for the fast response!
