### ISSUE TITLE
[Feature request] Add the ability to perform the BLS->0x01 changing using the deposit-data & keystore files generated by staking-deposit-cli

### ISSUE THREAD

**Issue by yzhuang** [wealdtech/ethdo#82]

**Comment by yzhuang** [comment]
Some users have forgotten their mnemonic but saved their deposit-data and keystore files.

**Comment by mcdee** [comment]
The mnemonic contains the information required to change credentials.  This information is not present in the deposit data or keystore.  If the mnemonic is lost then I'm afraid you will not be able to access the consensus funds, but can still obtain transaction fees from proposed blocks as has been the case since the merge.

**Comment by yzhuang** [comment]
Thanks for the info! @mcdee 
Could you help me understand what’s missing? Because I need to explain this to our users who forgot their mnemonic.

My understanding is that the following are needed:
- validator public key
- validator withdrawal credential
- The corresponding private key, which can come from either of:
  - Derived from the mnemonic with the path.
  - Stored in the keystore file and encrypted by a password.

What is the information that we cannot obtain from the deposit-data and keystore files?
Thank you 🙏

**Comment by mcdee** [comment]
The private key to change the credentials is not present in the keystore.
