### ISSUE TITLE
12 words mnemonics with mnemonic-passwords don't work

### ISSUE THREAD

**Issue by Sphearis** [wealdtech/ethdo#87]
I've got a particular setup for one of my deposits, I used a 12 words mnemonic (using "existing mnemonic" in deposit-cli 1.0, which were allowed) and also added a bit of security with a mnemonic password. 
Using a 24 words mnemonic + password works perfectly in ethdo, but using 12 words + password doesn't (mnemonic is invalid). 

This works, for example, in the deposit-cli where the password is another parameter: --mnemonic="12wordsmnemonic" and --mnemonic-password="password" are working there.

Could that feature be added/adapted?

**Comment by mcdee** [comment]
`ethdo` is designed to work with 24-word mnemonics, and due to the way it handles passphrases it isn't a simple change to make it work with 12-word mnemonics with passphrases.  To take a simple case, 24 words could be either a 24-word mnemonic or a 2-word mnemonic with a 12-word passphrase.  Being able to decide which is which could involve a lot of work, and edge cases that didn't do what was expected.

If you have a particular requirement for this you could build a local copy of `ethdo` after changing instances of `24` to `12` at https://github.com/wealdtech/ethdo/blob/master/util/mnemonic.go#L43-L48

**Comment by Sphearis** [comment]
That might be why I've seen some people having issues with their withdrawals with 12 words mnemonics (me included). I don't really know Go but I should be able to have my own modified copy working after doing some reading. Thank you.
